/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pGPIODModeReg = (uint32_t*)0x40020C00;
	uint32_t *pGPIODReg = (uint32_t*)0x40020C14;

	//enabling the clock
	*pClkCtrlReg|=0x08;

	//configure the IO pin as output
	//a.clear 24th and 25th positions
	*pGPIODModeReg&=0xFCFFFFFF;

	//b. make 24th bit position as 1
	*pGPIODModeReg|=0x01000000;

	//c. SET 12th bit of output data register
	*pGPIODReg|=0x1000;


    /* Loop forever */
	while(1);
}
