/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pGPIODModeReg = (uint32_t*)0x40020C00;
	uint32_t *pGPIODReg = (uint32_t*)0x40020C14;

	//enabling the clock
	*pClkCtrlReg|=(1 << 3);

	//configure the IO pin as output
	//a.clear 24th and 25th positions
	*pGPIODModeReg&= ~(3 << 24);

	//b. make 24th bit position as 1
	*pGPIODModeReg |= (1<<24);

	//c. SET 12th bit of output data register
	while(1)
	{
		*pGPIODReg |= (1 << 12);

		uint32_t i = 0;

		for(i = 0; i < 300000; i++);

		*pGPIODReg &= ~(1 << 12);

		for(i = 0; i < 300000; i++);
		}
}
